name: Deploy to Server

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Login to Docker Hub
            echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_IMAGE }}:latest
            
            # Stop and remove the old container if it exists
            docker stop myapp || true
            docker rm myapp || true
            
            # Run the new container
            docker run -d \
              --name myapp \
              --restart unless-stopped \
              -p 80:80 \
              ${{ secrets.DOCKER_IMAGE }}:latest
            
            # Clean up old images
            docker image prune -f