name: Deploy to Server

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to Server
        run: |
          # Login to Docker Hub
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          # Pull the latest image
          docker pull ${{ secrets.DOCKER_IMAGE }}:v1.1

          # Stop and remove the old container if it exists
          docker stop myapp || true
          docker rm myapp || true

          # Run the new container
          docker run -d \
            --name myapp \
            --restart unless-stopped \
            -p 8080:80 \
            ${{ secrets.DOCKER_IMAGE }}:v1.2

          # Clean up old images
          docker image prune -f
